import { expect, describe, it } from "vitest";
import {
  isExternalType,
  isUser,
  isPost,
  isHugeOnCombinations,
} from "./types_guards";
const invalidValue: any = Symbol("invalidValue");
const valid_ExternalType = [
  { id: "", body: "" },
  { id: "string", body: "" },
  { id: "string", body: "string" },
];
const invalid_ExternalType = [
  invalidValue,
  null,
  { id: invalidValue, body: "" },
  { body: "" },
  { id: "", body: invalidValue },
  { id: "string", body: invalidValue },
  { id: "string" },
];
describe("ExternalType", () => {
  it.for(valid_ExternalType)("valid", (value: unknown) => {
    expect(isExternalType(value)).toBe(true);
  });
  it.for(invalid_ExternalType)("invalid", (value: unknown) => {
    expect(isExternalType(value)).toBe(false);
  });
});
const valid_User = [
  {
    id: 0,
    login: "",
    bio: { first: "", last: "" },
    external: valid_ExternalType[0],
  },
  {
    id: 42,
    login: "",
    bio: { first: "", last: "" },
    external: valid_ExternalType[0],
  },
  {
    id: 42,
    login: "string",
    bio: { first: "", last: "" },
    external: valid_ExternalType[0],
  },
  {
    id: 42,
    login: "string",
    bio: { first: "string", last: "" },
    external: valid_ExternalType[0],
  },
  {
    id: 42,
    login: "string",
    bio: { first: "string", last: "string" },
    external: valid_ExternalType[0],
  },
];
const invalid_User = [
  invalidValue,
  null,
  {
    id: invalidValue,
    login: "",
    bio: { first: "", last: "" },
    external: valid_ExternalType[0],
  },
  { login: "", bio: { first: "", last: "" }, external: valid_ExternalType[0] },
  {
    id: 0,
    login: invalidValue,
    bio: { first: "", last: "" },
    external: valid_ExternalType[0],
  },
  {
    id: 42,
    login: invalidValue,
    bio: { first: "", last: "" },
    external: valid_ExternalType[0],
  },
  { id: 42, bio: { first: "", last: "" }, external: valid_ExternalType[0] },
  { id: 42, login: "", bio: invalidValue, external: valid_ExternalType[0] },
  {
    id: 42,
    login: "string",
    bio: invalidValue,
    external: valid_ExternalType[0],
  },
  { id: 42, login: "string", bio: null, external: valid_ExternalType[0] },
  {
    id: 42,
    login: "string",
    bio: { first: invalidValue, last: "" },
    external: valid_ExternalType[0],
  },
  {
    id: 42,
    login: "string",
    bio: { last: "" },
    external: valid_ExternalType[0],
  },
  {
    id: 42,
    login: "string",
    bio: { first: "", last: invalidValue },
    external: valid_ExternalType[0],
  },
  {
    id: 42,
    login: "string",
    bio: { first: "string", last: invalidValue },
    external: valid_ExternalType[0],
  },
  {
    id: 42,
    login: "string",
    bio: { first: "string" },
    external: valid_ExternalType[0],
  },
  { id: 42, login: "string", external: valid_ExternalType[0] },
  {
    id: 42,
    login: "string",
    bio: { first: "", last: "" },
    external: invalid_ExternalType[0],
  },
  {
    id: 42,
    login: "string",
    bio: { first: "string", last: "" },
    external: invalid_ExternalType[0],
  },
  {
    id: 42,
    login: "string",
    bio: { first: "string", last: "string" },
    external: invalid_ExternalType[0],
  },
  { id: 42, login: "string", bio: { first: "string", last: "string" } },
];
describe("User", () => {
  it.for(valid_User)("valid", (value: unknown) => {
    expect(isUser(value)).toBe(true);
  });
  it.for(invalid_User)("invalid", (value: unknown) => {
    expect(isUser(value)).toBe(false);
  });
});
const valid_Post = [
  {
    title: "",
    text: "",
    link: undefined,
    published: true,
    author: valid_User[0],
    more: [],
  },
  {
    title: "string",
    text: "",
    link: undefined,
    published: true,
    author: valid_User[0],
    more: [],
  },
  {
    title: "string",
    text: "string",
    link: undefined,
    published: true,
    author: valid_User[0],
    more: [],
  },
  {
    title: "string",
    text: "string",
    link: "",
    published: true,
    author: valid_User[0],
    more: [],
  },
  {
    title: "string",
    text: "string",
    link: "string",
    published: true,
    author: valid_User[0],
    more: [],
  },
  {
    title: "string",
    text: "string",
    published: true,
    author: valid_User[0],
    more: [],
  },
  {
    title: "string",
    text: "string",
    link: "string",
    published: false,
    author: valid_User[0],
    more: [],
  },
  {
    title: "string",
    text: "string",
    link: "string",
    published: false,
    author: valid_User[0],
    more: [""],
  },
  {
    title: "string",
    text: "string",
    link: "string",
    published: false,
    author: valid_User[0],
    more: ["string"],
  },
  {
    title: "string",
    text: "string",
    link: "string",
    published: false,
    author: valid_User[0],
    more: [0],
  },
  {
    title: "string",
    text: "string",
    link: "string",
    published: false,
    author: valid_User[0],
    more: [42],
  },
];
const invalid_Post = [
  invalidValue,
  null,
  {
    title: invalidValue,
    text: "",
    link: undefined,
    published: true,
    author: valid_User[0],
    more: [],
  },
  {
    text: "",
    link: undefined,
    published: true,
    author: valid_User[0],
    more: [],
  },
  {
    title: "",
    text: invalidValue,
    link: undefined,
    published: true,
    author: valid_User[0],
    more: [],
  },
  {
    title: "string",
    text: invalidValue,
    link: undefined,
    published: true,
    author: valid_User[0],
    more: [],
  },
  {
    title: "string",
    link: undefined,
    published: true,
    author: valid_User[0],
    more: [],
  },
  {
    title: "string",
    text: "",
    link: invalidValue,
    published: true,
    author: valid_User[0],
    more: [],
  },
  {
    title: "string",
    text: "string",
    link: invalidValue,
    published: true,
    author: valid_User[0],
    more: [],
  },
  {
    title: "string",
    text: "string",
    link: undefined,
    published: invalidValue,
    author: valid_User[0],
    more: [],
  },
  {
    title: "string",
    text: "string",
    link: "",
    published: invalidValue,
    author: valid_User[0],
    more: [],
  },
  {
    title: "string",
    text: "string",
    link: "string",
    published: invalidValue,
    author: valid_User[0],
    more: [],
  },
  {
    title: "string",
    text: "string",
    link: "string",
    author: valid_User[0],
    more: [],
  },
  {
    title: "string",
    text: "string",
    link: "string",
    published: true,
    author: invalid_User[0],
    more: [],
  },
  {
    title: "string",
    text: "string",
    link: "string",
    published: false,
    author: invalid_User[0],
    more: [],
  },
  {
    title: "string",
    text: "string",
    link: "string",
    published: false,
    more: [],
  },
  {
    title: "string",
    text: "string",
    link: "string",
    published: false,
    author: valid_User[0],
    more: invalidValue,
  },
  {
    title: "string",
    text: "string",
    link: "string",
    published: false,
    author: valid_User[0],
    more: [invalidValue],
  },
  {
    title: "string",
    text: "string",
    link: "string",
    published: false,
    author: valid_User[0],
  },
];
describe("Post", () => {
  it.for(valid_Post)("valid", (value: unknown) => {
    expect(isPost(value)).toBe(true);
  });
  it.for(invalid_Post)("invalid", (value: unknown) => {
    expect(isPost(value)).toBe(false);
  });
});
const valid_HugeOnCombinations = [
  {
    a: undefined,
    b: undefined,
    c: undefined,
    d: undefined,
    e: undefined,
    f: undefined,
    g: undefined,
    h: undefined,
    i: undefined,
    j: undefined,
    k: undefined,
    l: undefined,
    m: undefined,
    n: undefined,
    o: undefined,
    p: undefined,
    q: undefined,
  },
  {
    a: "",
    b: undefined,
    c: undefined,
    d: undefined,
    e: undefined,
    f: undefined,
    g: undefined,
    h: undefined,
    i: undefined,
    j: undefined,
    k: undefined,
    l: undefined,
    m: undefined,
    n: undefined,
    o: undefined,
    p: undefined,
    q: undefined,
  },
  {
    a: "string",
    b: undefined,
    c: undefined,
    d: undefined,
    e: undefined,
    f: undefined,
    g: undefined,
    h: undefined,
    i: undefined,
    j: undefined,
    k: undefined,
    l: undefined,
    m: undefined,
    n: undefined,
    o: undefined,
    p: undefined,
    q: undefined,
  },
  {
    b: undefined,
    c: undefined,
    d: undefined,
    e: undefined,
    f: undefined,
    g: undefined,
    h: undefined,
    i: undefined,
    j: undefined,
    k: undefined,
    l: undefined,
    m: undefined,
    n: undefined,
    o: undefined,
    p: undefined,
    q: undefined,
  },
  {
    a: "string",
    b: "",
    c: undefined,
    d: undefined,
    e: undefined,
    f: undefined,
    g: undefined,
    h: undefined,
    i: undefined,
    j: undefined,
    k: undefined,
    l: undefined,
    m: undefined,
    n: undefined,
    o: undefined,
    p: undefined,
    q: undefined,
  },
  {
    a: "string",
    b: "string",
    c: undefined,
    d: undefined,
    e: undefined,
    f: undefined,
    g: undefined,
    h: undefined,
    i: undefined,
    j: undefined,
    k: undefined,
    l: undefined,
    m: undefined,
    n: undefined,
    o: undefined,
    p: undefined,
    q: undefined,
  },
  {
    a: "string",
    c: undefined,
    d: undefined,
    e: undefined,
    f: undefined,
    g: undefined,
    h: undefined,
    i: undefined,
    j: undefined,
    k: undefined,
    l: undefined,
    m: undefined,
    n: undefined,
    o: undefined,
    p: undefined,
    q: undefined,
  },
  {
    a: "string",
    b: "string",
    c: "",
    d: undefined,
    e: undefined,
    f: undefined,
    g: undefined,
    h: undefined,
    i: undefined,
    j: undefined,
    k: undefined,
    l: undefined,
    m: undefined,
    n: undefined,
    o: undefined,
    p: undefined,
    q: undefined,
  },
  {
    a: "string",
    b: "string",
    c: "string",
    d: undefined,
    e: undefined,
    f: undefined,
    g: undefined,
    h: undefined,
    i: undefined,
    j: undefined,
    k: undefined,
    l: undefined,
    m: undefined,
    n: undefined,
    o: undefined,
    p: undefined,
    q: undefined,
  },
  {
    a: "string",
    b: "string",
    d: undefined,
    e: undefined,
    f: undefined,
    g: undefined,
    h: undefined,
    i: undefined,
    j: undefined,
    k: undefined,
    l: undefined,
    m: undefined,
    n: undefined,
    o: undefined,
    p: undefined,
    q: undefined,
  },
  {
    a: "string",
    b: "string",
    c: "string",
    d: "",
    e: undefined,
    f: undefined,
    g: undefined,
    h: undefined,
    i: undefined,
    j: undefined,
    k: undefined,
    l: undefined,
    m: undefined,
    n: undefined,
    o: undefined,
    p: undefined,
    q: undefined,
  },
  {
    a: "string",
    b: "string",
    c: "string",
    d: "string",
    e: undefined,
    f: undefined,
    g: undefined,
    h: undefined,
    i: undefined,
    j: undefined,
    k: undefined,
    l: undefined,
    m: undefined,
    n: undefined,
    o: undefined,
    p: undefined,
    q: undefined,
  },
  {
    a: "string",
    b: "string",
    c: "string",
    e: undefined,
    f: undefined,
    g: undefined,
    h: undefined,
    i: undefined,
    j: undefined,
    k: undefined,
    l: undefined,
    m: undefined,
    n: undefined,
    o: undefined,
    p: undefined,
    q: undefined,
  },
  {
    a: "string",
    b: "string",
    c: "string",
    d: "string",
    e: "",
    f: undefined,
    g: undefined,
    h: undefined,
    i: undefined,
    j: undefined,
    k: undefined,
    l: undefined,
    m: undefined,
    n: undefined,
    o: undefined,
    p: undefined,
    q: undefined,
  },
  {
    a: "string",
    b: "string",
    c: "string",
    d: "string",
    e: "string",
    f: undefined,
    g: undefined,
    h: undefined,
    i: undefined,
    j: undefined,
    k: undefined,
    l: undefined,
    m: undefined,
    n: undefined,
    o: undefined,
    p: undefined,
    q: undefined,
  },
  {
    a: "string",
    b: "string",
    c: "string",
    d: "string",
    f: undefined,
    g: undefined,
    h: undefined,
    i: undefined,
    j: undefined,
    k: undefined,
    l: undefined,
    m: undefined,
    n: undefined,
    o: undefined,
    p: undefined,
    q: undefined,
  },
  {
    a: "string",
    b: "string",
    c: "string",
    d: "string",
    e: "string",
    f: "",
    g: undefined,
    h: undefined,
    i: undefined,
    j: undefined,
    k: undefined,
    l: undefined,
    m: undefined,
    n: undefined,
    o: undefined,
    p: undefined,
    q: undefined,
  },
  {
    a: "string",
    b: "string",
    c: "string",
    d: "string",
    e: "string",
    f: "string",
    g: undefined,
    h: undefined,
    i: undefined,
    j: undefined,
    k: undefined,
    l: undefined,
    m: undefined,
    n: undefined,
    o: undefined,
    p: undefined,
    q: undefined,
  },
  {
    a: "string",
    b: "string",
    c: "string",
    d: "string",
    e: "string",
    g: undefined,
    h: undefined,
    i: undefined,
    j: undefined,
    k: undefined,
    l: undefined,
    m: undefined,
    n: undefined,
    o: undefined,
    p: undefined,
    q: undefined,
  },
  {
    a: "string",
    b: "string",
    c: "string",
    d: "string",
    e: "string",
    f: "string",
    g: "",
    h: undefined,
    i: undefined,
    j: undefined,
    k: undefined,
    l: undefined,
    m: undefined,
    n: undefined,
    o: undefined,
    p: undefined,
    q: undefined,
  },
  {
    a: "string",
    b: "string",
    c: "string",
    d: "string",
    e: "string",
    f: "string",
    g: "string",
    h: undefined,
    i: undefined,
    j: undefined,
    k: undefined,
    l: undefined,
    m: undefined,
    n: undefined,
    o: undefined,
    p: undefined,
    q: undefined,
  },
  {
    a: "string",
    b: "string",
    c: "string",
    d: "string",
    e: "string",
    f: "string",
    h: undefined,
    i: undefined,
    j: undefined,
    k: undefined,
    l: undefined,
    m: undefined,
    n: undefined,
    o: undefined,
    p: undefined,
    q: undefined,
  },
  {
    a: "string",
    b: "string",
    c: "string",
    d: "string",
    e: "string",
    f: "string",
    g: "string",
    h: "",
    i: undefined,
    j: undefined,
    k: undefined,
    l: undefined,
    m: undefined,
    n: undefined,
    o: undefined,
    p: undefined,
    q: undefined,
  },
  {
    a: "string",
    b: "string",
    c: "string",
    d: "string",
    e: "string",
    f: "string",
    g: "string",
    h: "string",
    i: undefined,
    j: undefined,
    k: undefined,
    l: undefined,
    m: undefined,
    n: undefined,
    o: undefined,
    p: undefined,
    q: undefined,
  },
  {
    a: "string",
    b: "string",
    c: "string",
    d: "string",
    e: "string",
    f: "string",
    g: "string",
    i: undefined,
    j: undefined,
    k: undefined,
    l: undefined,
    m: undefined,
    n: undefined,
    o: undefined,
    p: undefined,
    q: undefined,
  },
  {
    a: "string",
    b: "string",
    c: "string",
    d: "string",
    e: "string",
    f: "string",
    g: "string",
    h: "string",
    i: "",
    j: undefined,
    k: undefined,
    l: undefined,
    m: undefined,
    n: undefined,
    o: undefined,
    p: undefined,
    q: undefined,
  },
  {
    a: "string",
    b: "string",
    c: "string",
    d: "string",
    e: "string",
    f: "string",
    g: "string",
    h: "string",
    i: "string",
    j: undefined,
    k: undefined,
    l: undefined,
    m: undefined,
    n: undefined,
    o: undefined,
    p: undefined,
    q: undefined,
  },
  {
    a: "string",
    b: "string",
    c: "string",
    d: "string",
    e: "string",
    f: "string",
    g: "string",
    h: "string",
    j: undefined,
    k: undefined,
    l: undefined,
    m: undefined,
    n: undefined,
    o: undefined,
    p: undefined,
    q: undefined,
  },
  {
    a: "string",
    b: "string",
    c: "string",
    d: "string",
    e: "string",
    f: "string",
    g: "string",
    h: "string",
    i: "string",
    j: "",
    k: undefined,
    l: undefined,
    m: undefined,
    n: undefined,
    o: undefined,
    p: undefined,
    q: undefined,
  },
  {
    a: "string",
    b: "string",
    c: "string",
    d: "string",
    e: "string",
    f: "string",
    g: "string",
    h: "string",
    i: "string",
    j: "string",
    k: undefined,
    l: undefined,
    m: undefined,
    n: undefined,
    o: undefined,
    p: undefined,
    q: undefined,
  },
  {
    a: "string",
    b: "string",
    c: "string",
    d: "string",
    e: "string",
    f: "string",
    g: "string",
    h: "string",
    i: "string",
    k: undefined,
    l: undefined,
    m: undefined,
    n: undefined,
    o: undefined,
    p: undefined,
    q: undefined,
  },
  {
    a: "string",
    b: "string",
    c: "string",
    d: "string",
    e: "string",
    f: "string",
    g: "string",
    h: "string",
    i: "string",
    j: "string",
    k: "",
    l: undefined,
    m: undefined,
    n: undefined,
    o: undefined,
    p: undefined,
    q: undefined,
  },
  {
    a: "string",
    b: "string",
    c: "string",
    d: "string",
    e: "string",
    f: "string",
    g: "string",
    h: "string",
    i: "string",
    j: "string",
    k: "string",
    l: undefined,
    m: undefined,
    n: undefined,
    o: undefined,
    p: undefined,
    q: undefined,
  },
  {
    a: "string",
    b: "string",
    c: "string",
    d: "string",
    e: "string",
    f: "string",
    g: "string",
    h: "string",
    i: "string",
    j: "string",
    l: undefined,
    m: undefined,
    n: undefined,
    o: undefined,
    p: undefined,
    q: undefined,
  },
  {
    a: "string",
    b: "string",
    c: "string",
    d: "string",
    e: "string",
    f: "string",
    g: "string",
    h: "string",
    i: "string",
    j: "string",
    k: "string",
    l: "",
    m: undefined,
    n: undefined,
    o: undefined,
    p: undefined,
    q: undefined,
  },
  {
    a: "string",
    b: "string",
    c: "string",
    d: "string",
    e: "string",
    f: "string",
    g: "string",
    h: "string",
    i: "string",
    j: "string",
    k: "string",
    l: "string",
    m: undefined,
    n: undefined,
    o: undefined,
    p: undefined,
    q: undefined,
  },
  {
    a: "string",
    b: "string",
    c: "string",
    d: "string",
    e: "string",
    f: "string",
    g: "string",
    h: "string",
    i: "string",
    j: "string",
    k: "string",
    m: undefined,
    n: undefined,
    o: undefined,
    p: undefined,
    q: undefined,
  },
  {
    a: "string",
    b: "string",
    c: "string",
    d: "string",
    e: "string",
    f: "string",
    g: "string",
    h: "string",
    i: "string",
    j: "string",
    k: "string",
    l: "string",
    m: "",
    n: undefined,
    o: undefined,
    p: undefined,
    q: undefined,
  },
  {
    a: "string",
    b: "string",
    c: "string",
    d: "string",
    e: "string",
    f: "string",
    g: "string",
    h: "string",
    i: "string",
    j: "string",
    k: "string",
    l: "string",
    m: "string",
    n: undefined,
    o: undefined,
    p: undefined,
    q: undefined,
  },
  {
    a: "string",
    b: "string",
    c: "string",
    d: "string",
    e: "string",
    f: "string",
    g: "string",
    h: "string",
    i: "string",
    j: "string",
    k: "string",
    l: "string",
    n: undefined,
    o: undefined,
    p: undefined,
    q: undefined,
  },
  {
    a: "string",
    b: "string",
    c: "string",
    d: "string",
    e: "string",
    f: "string",
    g: "string",
    h: "string",
    i: "string",
    j: "string",
    k: "string",
    l: "string",
    m: "string",
    n: "",
    o: undefined,
    p: undefined,
    q: undefined,
  },
  {
    a: "string",
    b: "string",
    c: "string",
    d: "string",
    e: "string",
    f: "string",
    g: "string",
    h: "string",
    i: "string",
    j: "string",
    k: "string",
    l: "string",
    m: "string",
    n: "string",
    o: undefined,
    p: undefined,
    q: undefined,
  },
  {
    a: "string",
    b: "string",
    c: "string",
    d: "string",
    e: "string",
    f: "string",
    g: "string",
    h: "string",
    i: "string",
    j: "string",
    k: "string",
    l: "string",
    m: "string",
    o: undefined,
    p: undefined,
    q: undefined,
  },
  {
    a: "string",
    b: "string",
    c: "string",
    d: "string",
    e: "string",
    f: "string",
    g: "string",
    h: "string",
    i: "string",
    j: "string",
    k: "string",
    l: "string",
    m: "string",
    n: "string",
    o: "",
    p: undefined,
    q: undefined,
  },
  {
    a: "string",
    b: "string",
    c: "string",
    d: "string",
    e: "string",
    f: "string",
    g: "string",
    h: "string",
    i: "string",
    j: "string",
    k: "string",
    l: "string",
    m: "string",
    n: "string",
    o: "string",
    p: undefined,
    q: undefined,
  },
  {
    a: "string",
    b: "string",
    c: "string",
    d: "string",
    e: "string",
    f: "string",
    g: "string",
    h: "string",
    i: "string",
    j: "string",
    k: "string",
    l: "string",
    m: "string",
    n: "string",
    p: undefined,
    q: undefined,
  },
  {
    a: "string",
    b: "string",
    c: "string",
    d: "string",
    e: "string",
    f: "string",
    g: "string",
    h: "string",
    i: "string",
    j: "string",
    k: "string",
    l: "string",
    m: "string",
    n: "string",
    o: "string",
    p: "",
    q: undefined,
  },
  {
    a: "string",
    b: "string",
    c: "string",
    d: "string",
    e: "string",
    f: "string",
    g: "string",
    h: "string",
    i: "string",
    j: "string",
    k: "string",
    l: "string",
    m: "string",
    n: "string",
    o: "string",
    p: "string",
    q: undefined,
  },
  {
    a: "string",
    b: "string",
    c: "string",
    d: "string",
    e: "string",
    f: "string",
    g: "string",
    h: "string",
    i: "string",
    j: "string",
    k: "string",
    l: "string",
    m: "string",
    n: "string",
    o: "string",
    q: undefined,
  },
  {
    a: "string",
    b: "string",
    c: "string",
    d: "string",
    e: "string",
    f: "string",
    g: "string",
    h: "string",
    i: "string",
    j: "string",
    k: "string",
    l: "string",
    m: "string",
    n: "string",
    o: "string",
    p: "string",
    q: "",
  },
  {
    a: "string",
    b: "string",
    c: "string",
    d: "string",
    e: "string",
    f: "string",
    g: "string",
    h: "string",
    i: "string",
    j: "string",
    k: "string",
    l: "string",
    m: "string",
    n: "string",
    o: "string",
    p: "string",
    q: "string",
  },
  {
    a: "string",
    b: "string",
    c: "string",
    d: "string",
    e: "string",
    f: "string",
    g: "string",
    h: "string",
    i: "string",
    j: "string",
    k: "string",
    l: "string",
    m: "string",
    n: "string",
    o: "string",
    p: "string",
  },
];
const invalid_HugeOnCombinations = [
  invalidValue,
  null,
  {
    a: invalidValue,
    b: undefined,
    c: undefined,
    d: undefined,
    e: undefined,
    f: undefined,
    g: undefined,
    h: undefined,
    i: undefined,
    j: undefined,
    k: undefined,
    l: undefined,
    m: undefined,
    n: undefined,
    o: undefined,
    p: undefined,
    q: undefined,
  },
  {
    a: undefined,
    b: invalidValue,
    c: undefined,
    d: undefined,
    e: undefined,
    f: undefined,
    g: undefined,
    h: undefined,
    i: undefined,
    j: undefined,
    k: undefined,
    l: undefined,
    m: undefined,
    n: undefined,
    o: undefined,
    p: undefined,
    q: undefined,
  },
  {
    a: "",
    b: invalidValue,
    c: undefined,
    d: undefined,
    e: undefined,
    f: undefined,
    g: undefined,
    h: undefined,
    i: undefined,
    j: undefined,
    k: undefined,
    l: undefined,
    m: undefined,
    n: undefined,
    o: undefined,
    p: undefined,
    q: undefined,
  },
  {
    a: "string",
    b: invalidValue,
    c: undefined,
    d: undefined,
    e: undefined,
    f: undefined,
    g: undefined,
    h: undefined,
    i: undefined,
    j: undefined,
    k: undefined,
    l: undefined,
    m: undefined,
    n: undefined,
    o: undefined,
    p: undefined,
    q: undefined,
  },
  {
    a: "string",
    b: undefined,
    c: invalidValue,
    d: undefined,
    e: undefined,
    f: undefined,
    g: undefined,
    h: undefined,
    i: undefined,
    j: undefined,
    k: undefined,
    l: undefined,
    m: undefined,
    n: undefined,
    o: undefined,
    p: undefined,
    q: undefined,
  },
  {
    a: "string",
    b: "",
    c: invalidValue,
    d: undefined,
    e: undefined,
    f: undefined,
    g: undefined,
    h: undefined,
    i: undefined,
    j: undefined,
    k: undefined,
    l: undefined,
    m: undefined,
    n: undefined,
    o: undefined,
    p: undefined,
    q: undefined,
  },
  {
    a: "string",
    b: "string",
    c: invalidValue,
    d: undefined,
    e: undefined,
    f: undefined,
    g: undefined,
    h: undefined,
    i: undefined,
    j: undefined,
    k: undefined,
    l: undefined,
    m: undefined,
    n: undefined,
    o: undefined,
    p: undefined,
    q: undefined,
  },
  {
    a: "string",
    b: "string",
    c: undefined,
    d: invalidValue,
    e: undefined,
    f: undefined,
    g: undefined,
    h: undefined,
    i: undefined,
    j: undefined,
    k: undefined,
    l: undefined,
    m: undefined,
    n: undefined,
    o: undefined,
    p: undefined,
    q: undefined,
  },
  {
    a: "string",
    b: "string",
    c: "",
    d: invalidValue,
    e: undefined,
    f: undefined,
    g: undefined,
    h: undefined,
    i: undefined,
    j: undefined,
    k: undefined,
    l: undefined,
    m: undefined,
    n: undefined,
    o: undefined,
    p: undefined,
    q: undefined,
  },
  {
    a: "string",
    b: "string",
    c: "string",
    d: invalidValue,
    e: undefined,
    f: undefined,
    g: undefined,
    h: undefined,
    i: undefined,
    j: undefined,
    k: undefined,
    l: undefined,
    m: undefined,
    n: undefined,
    o: undefined,
    p: undefined,
    q: undefined,
  },
  {
    a: "string",
    b: "string",
    c: "string",
    d: undefined,
    e: invalidValue,
    f: undefined,
    g: undefined,
    h: undefined,
    i: undefined,
    j: undefined,
    k: undefined,
    l: undefined,
    m: undefined,
    n: undefined,
    o: undefined,
    p: undefined,
    q: undefined,
  },
  {
    a: "string",
    b: "string",
    c: "string",
    d: "",
    e: invalidValue,
    f: undefined,
    g: undefined,
    h: undefined,
    i: undefined,
    j: undefined,
    k: undefined,
    l: undefined,
    m: undefined,
    n: undefined,
    o: undefined,
    p: undefined,
    q: undefined,
  },
  {
    a: "string",
    b: "string",
    c: "string",
    d: "string",
    e: invalidValue,
    f: undefined,
    g: undefined,
    h: undefined,
    i: undefined,
    j: undefined,
    k: undefined,
    l: undefined,
    m: undefined,
    n: undefined,
    o: undefined,
    p: undefined,
    q: undefined,
  },
  {
    a: "string",
    b: "string",
    c: "string",
    d: "string",
    e: undefined,
    f: invalidValue,
    g: undefined,
    h: undefined,
    i: undefined,
    j: undefined,
    k: undefined,
    l: undefined,
    m: undefined,
    n: undefined,
    o: undefined,
    p: undefined,
    q: undefined,
  },
  {
    a: "string",
    b: "string",
    c: "string",
    d: "string",
    e: "",
    f: invalidValue,
    g: undefined,
    h: undefined,
    i: undefined,
    j: undefined,
    k: undefined,
    l: undefined,
    m: undefined,
    n: undefined,
    o: undefined,
    p: undefined,
    q: undefined,
  },
  {
    a: "string",
    b: "string",
    c: "string",
    d: "string",
    e: "string",
    f: invalidValue,
    g: undefined,
    h: undefined,
    i: undefined,
    j: undefined,
    k: undefined,
    l: undefined,
    m: undefined,
    n: undefined,
    o: undefined,
    p: undefined,
    q: undefined,
  },
  {
    a: "string",
    b: "string",
    c: "string",
    d: "string",
    e: "string",
    f: undefined,
    g: invalidValue,
    h: undefined,
    i: undefined,
    j: undefined,
    k: undefined,
    l: undefined,
    m: undefined,
    n: undefined,
    o: undefined,
    p: undefined,
    q: undefined,
  },
  {
    a: "string",
    b: "string",
    c: "string",
    d: "string",
    e: "string",
    f: "",
    g: invalidValue,
    h: undefined,
    i: undefined,
    j: undefined,
    k: undefined,
    l: undefined,
    m: undefined,
    n: undefined,
    o: undefined,
    p: undefined,
    q: undefined,
  },
  {
    a: "string",
    b: "string",
    c: "string",
    d: "string",
    e: "string",
    f: "string",
    g: invalidValue,
    h: undefined,
    i: undefined,
    j: undefined,
    k: undefined,
    l: undefined,
    m: undefined,
    n: undefined,
    o: undefined,
    p: undefined,
    q: undefined,
  },
  {
    a: "string",
    b: "string",
    c: "string",
    d: "string",
    e: "string",
    f: "string",
    g: undefined,
    h: invalidValue,
    i: undefined,
    j: undefined,
    k: undefined,
    l: undefined,
    m: undefined,
    n: undefined,
    o: undefined,
    p: undefined,
    q: undefined,
  },
  {
    a: "string",
    b: "string",
    c: "string",
    d: "string",
    e: "string",
    f: "string",
    g: "",
    h: invalidValue,
    i: undefined,
    j: undefined,
    k: undefined,
    l: undefined,
    m: undefined,
    n: undefined,
    o: undefined,
    p: undefined,
    q: undefined,
  },
  {
    a: "string",
    b: "string",
    c: "string",
    d: "string",
    e: "string",
    f: "string",
    g: "string",
    h: invalidValue,
    i: undefined,
    j: undefined,
    k: undefined,
    l: undefined,
    m: undefined,
    n: undefined,
    o: undefined,
    p: undefined,
    q: undefined,
  },
  {
    a: "string",
    b: "string",
    c: "string",
    d: "string",
    e: "string",
    f: "string",
    g: "string",
    h: undefined,
    i: invalidValue,
    j: undefined,
    k: undefined,
    l: undefined,
    m: undefined,
    n: undefined,
    o: undefined,
    p: undefined,
    q: undefined,
  },
  {
    a: "string",
    b: "string",
    c: "string",
    d: "string",
    e: "string",
    f: "string",
    g: "string",
    h: "",
    i: invalidValue,
    j: undefined,
    k: undefined,
    l: undefined,
    m: undefined,
    n: undefined,
    o: undefined,
    p: undefined,
    q: undefined,
  },
  {
    a: "string",
    b: "string",
    c: "string",
    d: "string",
    e: "string",
    f: "string",
    g: "string",
    h: "string",
    i: invalidValue,
    j: undefined,
    k: undefined,
    l: undefined,
    m: undefined,
    n: undefined,
    o: undefined,
    p: undefined,
    q: undefined,
  },
  {
    a: "string",
    b: "string",
    c: "string",
    d: "string",
    e: "string",
    f: "string",
    g: "string",
    h: "string",
    i: undefined,
    j: invalidValue,
    k: undefined,
    l: undefined,
    m: undefined,
    n: undefined,
    o: undefined,
    p: undefined,
    q: undefined,
  },
  {
    a: "string",
    b: "string",
    c: "string",
    d: "string",
    e: "string",
    f: "string",
    g: "string",
    h: "string",
    i: "",
    j: invalidValue,
    k: undefined,
    l: undefined,
    m: undefined,
    n: undefined,
    o: undefined,
    p: undefined,
    q: undefined,
  },
  {
    a: "string",
    b: "string",
    c: "string",
    d: "string",
    e: "string",
    f: "string",
    g: "string",
    h: "string",
    i: "string",
    j: invalidValue,
    k: undefined,
    l: undefined,
    m: undefined,
    n: undefined,
    o: undefined,
    p: undefined,
    q: undefined,
  },
  {
    a: "string",
    b: "string",
    c: "string",
    d: "string",
    e: "string",
    f: "string",
    g: "string",
    h: "string",
    i: "string",
    j: undefined,
    k: invalidValue,
    l: undefined,
    m: undefined,
    n: undefined,
    o: undefined,
    p: undefined,
    q: undefined,
  },
  {
    a: "string",
    b: "string",
    c: "string",
    d: "string",
    e: "string",
    f: "string",
    g: "string",
    h: "string",
    i: "string",
    j: "",
    k: invalidValue,
    l: undefined,
    m: undefined,
    n: undefined,
    o: undefined,
    p: undefined,
    q: undefined,
  },
  {
    a: "string",
    b: "string",
    c: "string",
    d: "string",
    e: "string",
    f: "string",
    g: "string",
    h: "string",
    i: "string",
    j: "string",
    k: invalidValue,
    l: undefined,
    m: undefined,
    n: undefined,
    o: undefined,
    p: undefined,
    q: undefined,
  },
  {
    a: "string",
    b: "string",
    c: "string",
    d: "string",
    e: "string",
    f: "string",
    g: "string",
    h: "string",
    i: "string",
    j: "string",
    k: undefined,
    l: invalidValue,
    m: undefined,
    n: undefined,
    o: undefined,
    p: undefined,
    q: undefined,
  },
  {
    a: "string",
    b: "string",
    c: "string",
    d: "string",
    e: "string",
    f: "string",
    g: "string",
    h: "string",
    i: "string",
    j: "string",
    k: "",
    l: invalidValue,
    m: undefined,
    n: undefined,
    o: undefined,
    p: undefined,
    q: undefined,
  },
  {
    a: "string",
    b: "string",
    c: "string",
    d: "string",
    e: "string",
    f: "string",
    g: "string",
    h: "string",
    i: "string",
    j: "string",
    k: "string",
    l: invalidValue,
    m: undefined,
    n: undefined,
    o: undefined,
    p: undefined,
    q: undefined,
  },
  {
    a: "string",
    b: "string",
    c: "string",
    d: "string",
    e: "string",
    f: "string",
    g: "string",
    h: "string",
    i: "string",
    j: "string",
    k: "string",
    l: undefined,
    m: invalidValue,
    n: undefined,
    o: undefined,
    p: undefined,
    q: undefined,
  },
  {
    a: "string",
    b: "string",
    c: "string",
    d: "string",
    e: "string",
    f: "string",
    g: "string",
    h: "string",
    i: "string",
    j: "string",
    k: "string",
    l: "",
    m: invalidValue,
    n: undefined,
    o: undefined,
    p: undefined,
    q: undefined,
  },
  {
    a: "string",
    b: "string",
    c: "string",
    d: "string",
    e: "string",
    f: "string",
    g: "string",
    h: "string",
    i: "string",
    j: "string",
    k: "string",
    l: "string",
    m: invalidValue,
    n: undefined,
    o: undefined,
    p: undefined,
    q: undefined,
  },
  {
    a: "string",
    b: "string",
    c: "string",
    d: "string",
    e: "string",
    f: "string",
    g: "string",
    h: "string",
    i: "string",
    j: "string",
    k: "string",
    l: "string",
    m: undefined,
    n: invalidValue,
    o: undefined,
    p: undefined,
    q: undefined,
  },
  {
    a: "string",
    b: "string",
    c: "string",
    d: "string",
    e: "string",
    f: "string",
    g: "string",
    h: "string",
    i: "string",
    j: "string",
    k: "string",
    l: "string",
    m: "",
    n: invalidValue,
    o: undefined,
    p: undefined,
    q: undefined,
  },
  {
    a: "string",
    b: "string",
    c: "string",
    d: "string",
    e: "string",
    f: "string",
    g: "string",
    h: "string",
    i: "string",
    j: "string",
    k: "string",
    l: "string",
    m: "string",
    n: invalidValue,
    o: undefined,
    p: undefined,
    q: undefined,
  },
  {
    a: "string",
    b: "string",
    c: "string",
    d: "string",
    e: "string",
    f: "string",
    g: "string",
    h: "string",
    i: "string",
    j: "string",
    k: "string",
    l: "string",
    m: "string",
    n: undefined,
    o: invalidValue,
    p: undefined,
    q: undefined,
  },
  {
    a: "string",
    b: "string",
    c: "string",
    d: "string",
    e: "string",
    f: "string",
    g: "string",
    h: "string",
    i: "string",
    j: "string",
    k: "string",
    l: "string",
    m: "string",
    n: "",
    o: invalidValue,
    p: undefined,
    q: undefined,
  },
  {
    a: "string",
    b: "string",
    c: "string",
    d: "string",
    e: "string",
    f: "string",
    g: "string",
    h: "string",
    i: "string",
    j: "string",
    k: "string",
    l: "string",
    m: "string",
    n: "string",
    o: invalidValue,
    p: undefined,
    q: undefined,
  },
  {
    a: "string",
    b: "string",
    c: "string",
    d: "string",
    e: "string",
    f: "string",
    g: "string",
    h: "string",
    i: "string",
    j: "string",
    k: "string",
    l: "string",
    m: "string",
    n: "string",
    o: undefined,
    p: invalidValue,
    q: undefined,
  },
  {
    a: "string",
    b: "string",
    c: "string",
    d: "string",
    e: "string",
    f: "string",
    g: "string",
    h: "string",
    i: "string",
    j: "string",
    k: "string",
    l: "string",
    m: "string",
    n: "string",
    o: "",
    p: invalidValue,
    q: undefined,
  },
  {
    a: "string",
    b: "string",
    c: "string",
    d: "string",
    e: "string",
    f: "string",
    g: "string",
    h: "string",
    i: "string",
    j: "string",
    k: "string",
    l: "string",
    m: "string",
    n: "string",
    o: "string",
    p: invalidValue,
    q: undefined,
  },
  {
    a: "string",
    b: "string",
    c: "string",
    d: "string",
    e: "string",
    f: "string",
    g: "string",
    h: "string",
    i: "string",
    j: "string",
    k: "string",
    l: "string",
    m: "string",
    n: "string",
    o: "string",
    p: undefined,
    q: invalidValue,
  },
  {
    a: "string",
    b: "string",
    c: "string",
    d: "string",
    e: "string",
    f: "string",
    g: "string",
    h: "string",
    i: "string",
    j: "string",
    k: "string",
    l: "string",
    m: "string",
    n: "string",
    o: "string",
    p: "",
    q: invalidValue,
  },
  {
    a: "string",
    b: "string",
    c: "string",
    d: "string",
    e: "string",
    f: "string",
    g: "string",
    h: "string",
    i: "string",
    j: "string",
    k: "string",
    l: "string",
    m: "string",
    n: "string",
    o: "string",
    p: "string",
    q: invalidValue,
  },
];
describe("HugeOnCombinations", () => {
  it.for(valid_HugeOnCombinations)("valid", (value: unknown) => {
    expect(isHugeOnCombinations(value)).toBe(true);
  });
  it.for(invalid_HugeOnCombinations)("invalid", (value: unknown) => {
    expect(isHugeOnCombinations(value)).toBe(false);
  });
});
