import { expect, describe, it } from "vitest";
import { isUser, isPost } from "./types_guards";
const invalidValue: any = Symbol("invalidValue");
const valid_User = [
  { id: 0, login: "string", bio: { first: "string", last: "string" } },
  { id: 42, login: "string", bio: { first: "string", last: "string" } },
];
const invalid_User = [
  null,
  { login: "string", bio: { first: "string", last: "string" } },
  {
    id: invalidValue,
    login: "string",
    bio: { first: "string", last: "string" },
  },
  { id: 0, bio: { first: "string", last: "string" } },
  { id: 0, login: invalidValue, bio: { first: "string", last: "string" } },
  { id: 0, login: "string" },
  { id: 0, login: "string", bio: null },
  { id: 0, login: "string", bio: { last: "string" } },
  { id: 0, login: "string", bio: { first: invalidValue, last: "string" } },
  { id: 0, login: "string", bio: { first: "string" } },
  { id: 0, login: "string", bio: { first: "string", last: invalidValue } },
  { id: 42, bio: { first: "string", last: "string" } },
  { id: 42, login: invalidValue, bio: { first: "string", last: "string" } },
  { id: 42, login: "string" },
  { id: 42, login: "string", bio: null },
  { id: 42, login: "string", bio: { last: "string" } },
  { id: 42, login: "string", bio: { first: invalidValue, last: "string" } },
  { id: 42, login: "string", bio: { first: "string" } },
  { id: 42, login: "string", bio: { first: "string", last: invalidValue } },
];
describe("User", () => {
  it.for(valid_User)("valid", (value) => {
    expect(isUser(value)).toBe(true);
  });
  it.for(invalid_User)("invalid", (value) => {
    expect(isUser(value)).toBe(false);
  });
});
const valid_Post = [
  {
    title: "string",
    text: "string",
    link: "string",
    published: true,
    author: valid_User[1],
    more: [],
  },
  {
    title: "string",
    text: "string",
    link: "string",
    published: true,
    author: valid_User[1],
    more: ["string"],
  },
  {
    title: "string",
    text: "string",
    link: "string",
    published: true,
    author: valid_User[1],
    more: [0],
  },
  {
    title: "string",
    text: "string",
    link: "string",
    published: true,
    author: valid_User[1],
    more: [42],
  },
  {
    title: "string",
    text: "string",
    link: "string",
    published: false,
    author: valid_User[1],
    more: [],
  },
  {
    title: "string",
    text: "string",
    link: "string",
    published: false,
    author: valid_User[1],
    more: ["string"],
  },
  {
    title: "string",
    text: "string",
    link: "string",
    published: false,
    author: valid_User[1],
    more: [0],
  },
  {
    title: "string",
    text: "string",
    link: "string",
    published: false,
    author: valid_User[1],
    more: [42],
  },
];
const invalid_Post = [
  null,
  {
    text: "string",
    link: "string",
    published: true,
    author: valid_User[1],
    more: [],
  },
  {
    text: "string",
    link: "string",
    published: true,
    author: valid_User[1],
    more: ["string"],
  },
  {
    text: "string",
    link: "string",
    published: true,
    author: valid_User[1],
    more: [0],
  },
  {
    text: "string",
    link: "string",
    published: true,
    author: valid_User[1],
    more: [42],
  },
  {
    text: "string",
    link: "string",
    published: false,
    author: valid_User[1],
    more: [],
  },
  {
    text: "string",
    link: "string",
    published: false,
    author: valid_User[1],
    more: ["string"],
  },
  {
    text: "string",
    link: "string",
    published: false,
    author: valid_User[1],
    more: [0],
  },
  {
    text: "string",
    link: "string",
    published: false,
    author: valid_User[1],
    more: [42],
  },
  {
    title: invalidValue,
    text: "string",
    link: "string",
    published: true,
    author: valid_User[1],
    more: [],
  },
  {
    title: invalidValue,
    text: "string",
    link: "string",
    published: true,
    author: valid_User[1],
    more: ["string"],
  },
  {
    title: invalidValue,
    text: "string",
    link: "string",
    published: true,
    author: valid_User[1],
    more: [0],
  },
  {
    title: invalidValue,
    text: "string",
    link: "string",
    published: true,
    author: valid_User[1],
    more: [42],
  },
  {
    title: invalidValue,
    text: "string",
    link: "string",
    published: false,
    author: valid_User[1],
    more: [],
  },
  {
    title: invalidValue,
    text: "string",
    link: "string",
    published: false,
    author: valid_User[1],
    more: ["string"],
  },
  {
    title: invalidValue,
    text: "string",
    link: "string",
    published: false,
    author: valid_User[1],
    more: [0],
  },
  {
    title: invalidValue,
    text: "string",
    link: "string",
    published: false,
    author: valid_User[1],
    more: [42],
  },
  {
    title: "string",
    link: "string",
    published: true,
    author: valid_User[1],
    more: [],
  },
  {
    title: "string",
    link: "string",
    published: true,
    author: valid_User[1],
    more: ["string"],
  },
  {
    title: "string",
    link: "string",
    published: true,
    author: valid_User[1],
    more: [0],
  },
  {
    title: "string",
    link: "string",
    published: true,
    author: valid_User[1],
    more: [42],
  },
  {
    title: "string",
    link: "string",
    published: false,
    author: valid_User[1],
    more: [],
  },
  {
    title: "string",
    link: "string",
    published: false,
    author: valid_User[1],
    more: ["string"],
  },
  {
    title: "string",
    link: "string",
    published: false,
    author: valid_User[1],
    more: [0],
  },
  {
    title: "string",
    link: "string",
    published: false,
    author: valid_User[1],
    more: [42],
  },
  {
    title: "string",
    text: invalidValue,
    link: "string",
    published: true,
    author: valid_User[1],
    more: [],
  },
  {
    title: "string",
    text: invalidValue,
    link: "string",
    published: true,
    author: valid_User[1],
    more: ["string"],
  },
  {
    title: "string",
    text: invalidValue,
    link: "string",
    published: true,
    author: valid_User[1],
    more: [0],
  },
  {
    title: "string",
    text: invalidValue,
    link: "string",
    published: true,
    author: valid_User[1],
    more: [42],
  },
  {
    title: "string",
    text: invalidValue,
    link: "string",
    published: false,
    author: valid_User[1],
    more: [],
  },
  {
    title: "string",
    text: invalidValue,
    link: "string",
    published: false,
    author: valid_User[1],
    more: ["string"],
  },
  {
    title: "string",
    text: invalidValue,
    link: "string",
    published: false,
    author: valid_User[1],
    more: [0],
  },
  {
    title: "string",
    text: invalidValue,
    link: "string",
    published: false,
    author: valid_User[1],
    more: [42],
  },
  {
    title: "string",
    text: "string",
    published: true,
    author: valid_User[1],
    more: [],
  },
  {
    title: "string",
    text: "string",
    published: true,
    author: valid_User[1],
    more: ["string"],
  },
  {
    title: "string",
    text: "string",
    published: true,
    author: valid_User[1],
    more: [0],
  },
  {
    title: "string",
    text: "string",
    published: true,
    author: valid_User[1],
    more: [42],
  },
  {
    title: "string",
    text: "string",
    published: false,
    author: valid_User[1],
    more: [],
  },
  {
    title: "string",
    text: "string",
    published: false,
    author: valid_User[1],
    more: ["string"],
  },
  {
    title: "string",
    text: "string",
    published: false,
    author: valid_User[1],
    more: [0],
  },
  {
    title: "string",
    text: "string",
    published: false,
    author: valid_User[1],
    more: [42],
  },
  {
    title: "string",
    text: "string",
    link: invalidValue,
    published: true,
    author: valid_User[1],
    more: [],
  },
  {
    title: "string",
    text: "string",
    link: invalidValue,
    published: true,
    author: valid_User[1],
    more: ["string"],
  },
  {
    title: "string",
    text: "string",
    link: invalidValue,
    published: true,
    author: valid_User[1],
    more: [0],
  },
  {
    title: "string",
    text: "string",
    link: invalidValue,
    published: true,
    author: valid_User[1],
    more: [42],
  },
  {
    title: "string",
    text: "string",
    link: invalidValue,
    published: false,
    author: valid_User[1],
    more: [],
  },
  {
    title: "string",
    text: "string",
    link: invalidValue,
    published: false,
    author: valid_User[1],
    more: ["string"],
  },
  {
    title: "string",
    text: "string",
    link: invalidValue,
    published: false,
    author: valid_User[1],
    more: [0],
  },
  {
    title: "string",
    text: "string",
    link: invalidValue,
    published: false,
    author: valid_User[1],
    more: [42],
  },
  {
    title: "string",
    text: "string",
    link: "string",
    author: valid_User[1],
    more: [],
  },
  {
    title: "string",
    text: "string",
    link: "string",
    author: valid_User[1],
    more: ["string"],
  },
  {
    title: "string",
    text: "string",
    link: "string",
    author: valid_User[1],
    more: [0],
  },
  {
    title: "string",
    text: "string",
    link: "string",
    author: valid_User[1],
    more: [42],
  },
  {
    title: "string",
    text: "string",
    link: "string",
    published: invalidValue,
    author: valid_User[1],
    more: [],
  },
  {
    title: "string",
    text: "string",
    link: "string",
    published: invalidValue,
    author: valid_User[1],
    more: ["string"],
  },
  {
    title: "string",
    text: "string",
    link: "string",
    published: invalidValue,
    author: valid_User[1],
    more: [0],
  },
  {
    title: "string",
    text: "string",
    link: "string",
    published: invalidValue,
    author: valid_User[1],
    more: [42],
  },
  {
    title: "string",
    text: "string",
    link: "string",
    published: true,
    more: [],
  },
  {
    title: "string",
    text: "string",
    link: "string",
    published: true,
    more: ["string"],
  },
  {
    title: "string",
    text: "string",
    link: "string",
    published: true,
    more: [0],
  },
  {
    title: "string",
    text: "string",
    link: "string",
    published: true,
    more: [42],
  },
  {
    title: "string",
    text: "string",
    link: "string",
    published: true,
    author: invalid_User[1],
    more: [],
  },
  {
    title: "string",
    text: "string",
    link: "string",
    published: true,
    author: invalid_User[1],
    more: ["string"],
  },
  {
    title: "string",
    text: "string",
    link: "string",
    published: true,
    author: invalid_User[1],
    more: [0],
  },
  {
    title: "string",
    text: "string",
    link: "string",
    published: true,
    author: invalid_User[1],
    more: [42],
  },
  {
    title: "string",
    text: "string",
    link: "string",
    published: true,
    author: valid_User[1],
  },
  {
    title: "string",
    text: "string",
    link: "string",
    published: true,
    author: valid_User[1],
    more: invalidValue,
  },
  {
    title: "string",
    text: "string",
    link: "string",
    published: true,
    author: valid_User[1],
    more: [invalidValue],
  },
  {
    title: "string",
    text: "string",
    link: "string",
    published: false,
    more: [],
  },
  {
    title: "string",
    text: "string",
    link: "string",
    published: false,
    more: ["string"],
  },
  {
    title: "string",
    text: "string",
    link: "string",
    published: false,
    more: [0],
  },
  {
    title: "string",
    text: "string",
    link: "string",
    published: false,
    more: [42],
  },
  {
    title: "string",
    text: "string",
    link: "string",
    published: false,
    author: invalid_User[1],
    more: [],
  },
  {
    title: "string",
    text: "string",
    link: "string",
    published: false,
    author: invalid_User[1],
    more: ["string"],
  },
  {
    title: "string",
    text: "string",
    link: "string",
    published: false,
    author: invalid_User[1],
    more: [0],
  },
  {
    title: "string",
    text: "string",
    link: "string",
    published: false,
    author: invalid_User[1],
    more: [42],
  },
  {
    title: "string",
    text: "string",
    link: "string",
    published: false,
    author: valid_User[1],
  },
  {
    title: "string",
    text: "string",
    link: "string",
    published: false,
    author: valid_User[1],
    more: invalidValue,
  },
  {
    title: "string",
    text: "string",
    link: "string",
    published: false,
    author: valid_User[1],
    more: [invalidValue],
  },
];
describe("Post", () => {
  it.for(valid_Post)("valid", (value) => {
    expect(isPost(value)).toBe(true);
  });
  it.for(invalid_Post)("invalid", (value) => {
    expect(isPost(value)).toBe(false);
  });
});
